//! Host-fn binding signatures — one function per WIT entry in `wit/host.wit`.
//!
//! Bodies are unimplemented stubs (`todo!()`).  The type signatures enforce the
//! WorkspaceCtx-first calling convention and make the wrong thing inexpressible:
//! every write-path function accepts only `ctx: WorkspaceCtx` plus domain
//! params; there is no `workspace_id: String` parameter anywhere in this module.
//! A caller that tries to pass a bare workspace ID to a write-path function
//! finds no matching parameter slot — the constraint is structural, not enforced
//! by a runtime check.
//!
//! # Why workspace-id is inexpressible as a standalone param
//!
//! The workspace identity lives inside `WorkspaceCtx.workspace_id`.  The host
//! derives it before constructing the `WorkspaceCtx` value; the only way to
//! supply a workspace identity to a host-fn is to construct a `WorkspaceCtx`
//! and pass it as `ctx`.  There is no `workspace_id: String` typed parameter
//! to pass, so R-0012-d / R-0003-d violations cannot be expressed at the Rust
//! type level.

use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use uuid::Uuid;

use super::{DispatchError, DispatchOutcome, DispatchWrapper, Stability};
use crate::auth::workspace_ctx::WorkspaceCtx;

// ---------------------------------------------------------------------------
// Shared types (mirror of wit types)
// ---------------------------------------------------------------------------

/// Opaque JSON value — serialised as a UTF-8 string.
/// Mirrors `type json = string` in WIT (R-0012-f: never list<u8>).
pub type Json = String;

// ---------------------------------------------------------------------------
// T7 — Branch-2 fenced in-memory artifact store (the ONLY sanctioned stand-in
// on the slice-1 reachable path)
// ---------------------------------------------------------------------------
//
// This is a deliberate throwaway: a small in-memory map fenced INSIDE the
// host-fn layer, NOT an extension of the `Storage`/`MemStorage` trait. That
// trait is a generic `Record { key, value }` transaction seam; artifact-shaping
// it would re-couple this code to the in-flight storage design (the storage ADR
// + adapter work). Keeping the map here decouples slice 1 from that design; T13
// swaps it for real `Storage`/Postgres and removes this map entirely.
//
// Workspace isolation (R-0006-d) is enforced at the map key: entries are keyed
// by `(workspace_id, id)`, so a `get` under a different workspace cannot resolve
// another workspace's artifact (a cross-workspace get returns `None`). The
// `workspace_id` is the host-derived scoping key (read from store data, never a
// guest-supplied value — R-0006-b/e).

/// One artifact row in the fenced map (the slice-1 stub shape).
#[derive(Debug, Clone)]
struct StoredArtifact {
    /// The artifact type name (e.g. `"echo_fixture"`). Read by
    /// `fenced_artifact_list` for the type filter (T12); not surfaced by `get`
    /// (which round-trips frontmatter/body content).
    type_name: String,
    /// The frontmatter JSON-as-string (the create `payload` round-trips here).
    frontmatter: String,
    /// The optional body text.
    body: Option<String>,
}

/// The shared, process-wide fenced artifact store. Cloning shares the underlying
/// map (Arc-backed) so a `create` on one pooled instance is visible to a later
/// `get` on another instance within the host process. Keyed by
/// `(workspace_id, id)` for workspace isolation (R-0006-d).
#[derive(Debug, Clone, Default)]
pub struct FencedArtifactStore {
    inner: Arc<Mutex<HashMap<(Uuid, String), StoredArtifact>>>,
}

impl FencedArtifactStore {
    /// Construct an empty fenced store.
    pub fn new() -> Self {
        Self::default()
    }
}

/// `artifact-create` (T7 fenced body): generate a real ULID, persist
/// `(id, type, frontmatter, body)` under `workspace_id`, and return the id.
///
/// The ULID is generated by the `ulid` crate (Crockford base32, 26 chars) — a
/// real, monotonic-by-default identifier, never a constant or fake. Persistence
/// is the fenced map; the WHERE-clause discriminator is the `workspace_id` key
/// component (R-0006-d), derived host-side (R-0006-b/e).
pub fn fenced_artifact_create(
    store: &FencedArtifactStore,
    workspace_id: Uuid,
    type_name: &str,
    frontmatter: Json,
    body: Option<String>,
) -> String {
    let id = ulid::Ulid::new().to_string();
    let row = StoredArtifact {
        type_name: type_name.to_owned(),
        frontmatter,
        body,
    };
    let mut map = store.inner.lock().unwrap_or_else(|e| e.into_inner());
    map.insert((workspace_id, id.clone()), row);
    id
}

/// `artifact-get` (T7 fenced body): read back the artifact for `(workspace_id,
/// id)`; `None` if absent or owned by a different workspace (R-0006-d isolation).
///
/// The returned string round-trips the stored content so the original create
/// `payload` is recoverable (reconciliation R2): the frontmatter is surfaced,
/// with the body appended when present.
pub fn fenced_artifact_get(
    store: &FencedArtifactStore,
    workspace_id: Uuid,
    id: &str,
) -> Option<String> {
    let map = store.inner.lock().unwrap_or_else(|e| e.into_inner());
    // WHERE-clause shape (fenced-map analogue): workspace_id = $1 AND id = $2.
    // The workspace_id key component is the R-0006-d discriminator — a get under
    // a different workspace_id simply does not match this entry.
    map.get(&(workspace_id, id.to_owned())).map(|row| {
        // Surface the stored content as text so the created payload round-trips.
        // The frontmatter carries the create payload; append the body if present.
        match &row.body {
            Some(body) => format!("{}\n{}", row.frontmatter, body),
            None => row.frontmatter.clone(),
        }
    })
    // `type_name` is retained on the row for the `list` body below; not surfaced
    // by `get` (which round-trips frontmatter/body content).
}

/// `artifact-list` (T7 fenced body): return the ids of artifacts owned by
/// `workspace_id` whose stored type matches `type_name` (R-0006-d isolation).
///
/// Unlike `fenced_artifact_get` (a single-key `(workspace_id, id)` lookup), this
/// ITERATES the fenced map. The workspace scoping is therefore enforced on every
/// entry, not by a key constructed from the caller: only entries whose key
/// workspace component equals the host-derived `workspace_id` AND whose stored
/// `type_name` matches are returned. A row owned by a different workspace can
/// never leak into the result — `key.0` is the R-0006-d discriminator, exactly
/// as in `fenced_artifact_get`. `workspace_id` is the host-derived scoping key
/// (read from store data, never a guest-supplied value — R-0006-b/e).
///
/// `filters` is threaded through for wiring completeness but NOT applied this
/// slice: scoping is `workspace_id` + `type_name` only. Predicate logic on a
/// security verb with zero red-test coverage would be unverified, so it is
/// deferred (see the brain #1846 marker at the filter site below).
pub fn fenced_artifact_list(
    store: &FencedArtifactStore,
    workspace_id: Uuid,
    type_name: &str,
    _filters: Json,
) -> Vec<String> {
    let map = store.inner.lock().unwrap_or_else(|e| e.into_inner());
    // WHERE-clause shape (fenced-map analogue): workspace_id = $1 AND type_name = $2.
    // The workspace_id key component is the R-0006-d discriminator — an entry
    // owned by a different workspace simply does not match and cannot leak.
    map.iter()
        .filter(|((ws, _id), row)| {
            // filter predicate application deferred — brain #1846
            *ws == workspace_id && row.type_name == type_name
        })
        .map(|((_ws, id), _row)| id.clone())
        .collect()
}

/// `artifact-update` (T7 fenced body): merge `frontmatter_patch` into the stored
/// frontmatter and (when `body` is `Some`) replace the body, for the artifact
/// keyed `(workspace_id, id)` in the CALLER's workspace (R-0006-d isolation).
///
/// WHERE-clause shape (fenced-map analogue): `workspace_id = $1 AND id = $2`. The
/// `workspace_id` key component is the host-derived (R-0006-b/e) discriminator —
/// an `(workspace_id, id)` not present in the caller's workspace simply MISSES, so
/// the update is a SILENT NO-OP and nothing is modified. A different workspace's
/// artifact is keyed under a different `workspace_id` and is therefore unreachable:
/// workspace B updating A's id is a no-op and A's artifact is left intact
/// (cross-tenant WRITE isolation).
///
/// Merge semantics: patch keys overwrite/add; keys absent from the patch are
/// PRESERVED. `body`: `Some(b)` replaces the stored body; `None` leaves it
/// unchanged. Both the stored frontmatter and the patch are parsed DEFENSIVELY —
/// `create`'s `json_value_to_payload_string` can store a non-object value (a raw
/// string) for a non-object payload, so this NEVER `unwrap()`s a parse and never
/// panics (a non-object/malformed base falls back to an empty object; a
/// non-object/malformed patch contributes no keys).
pub fn fenced_artifact_update(
    store: &FencedArtifactStore,
    workspace_id: Uuid,
    id: &str,
    frontmatter_patch: Json,
    body: Option<String>,
) {
    let mut map = store.inner.lock().unwrap_or_else(|e| e.into_inner());
    // Single-key `(workspace_id, id)` lookup, exactly as `fenced_artifact_get`. A
    // miss (absent id, or an id owned by a different workspace) yields `None` here,
    // so the whole body is skipped — the no-op-on-miss tenant-isolation behavior.
    if let Some(row) = map.get_mut(&(workspace_id, id.to_owned())) {
        row.frontmatter = merge_frontmatter(&row.frontmatter, &frontmatter_patch);
        // `Some` replaces the stored body; `None` leaves the existing body intact.
        if let Some(new_body) = body {
            row.body = Some(new_body);
        }
    }
}

/// JSON-merge `patch` over `stored`, returning compact JSON object text.
///
/// Defensive (no-panic, advisor-flagged): the base is `stored` parsed as a JSON
/// object, falling back to an empty object when `stored` is not object-shaped
/// (a raw string from `create`'s non-object payload path). The patch contributes
/// keys only when it parses as a JSON object; patch keys overwrite/add, base keys
/// absent from the patch are preserved. Neither parse is ever `unwrap()`ed.
fn merge_frontmatter(stored: &str, patch: &str) -> String {
    use serde_json::{Map, Value};

    let mut base: Map<String, Value> = match serde_json::from_str::<Value>(stored) {
        Ok(Value::Object(m)) => m,
        _ => Map::new(),
    };
    if let Ok(Value::Object(patch_map)) = serde_json::from_str::<Value>(patch) {
        for (k, v) in patch_map {
            base.insert(k, v);
        }
    }
    Value::Object(base).to_string()
}

// ---------------------------------------------------------------------------
// artifact interface
// ---------------------------------------------------------------------------

/// Stability constant shared by all `artifact` functions.
const ARTIFACT_STABILITY: Stability = Stability::Stable;

/// `artifact-create` — creates a new artifact and returns its generated id.
///
/// R-0012-a, R-0006-a
pub fn artifact_create(
    _ctx: WorkspaceCtx,
    _type_name: &str,
    _frontmatter: Json,
    _body: Option<String>,
) -> Result<DispatchOutcome<String>, DispatchError> {
    DispatchWrapper::invoke(&ARTIFACT_STABILITY, "artifact-create", || {
        todo!("artifact-create: stub — storage wired in Task 5")
    })
}

/// `artifact-update` — patches frontmatter and/or body of an existing artifact.
///
/// R-0012-a, R-0006-a
pub fn artifact_update(
    _ctx: WorkspaceCtx,
    _id: &str,
    _frontmatter_patch: Json,
    _body: Option<String>,
) -> Result<DispatchOutcome<()>, DispatchError> {
    DispatchWrapper::invoke(&ARTIFACT_STABILITY, "artifact-update", || {
        todo!("artifact-update: stub — storage wired in Task 5")
    })
}

/// `artifact-get` — retrieves a single artifact by id.
///
/// The WHERE clause includes `workspace_id = ctx.workspace_id()` to scope the
/// query to the caller's workspace (R-0006-d). Storage wiring lands in Task 5.
///
/// R-0012-a, R-0006-a, R-0006-d
pub fn artifact_get(
    ctx: WorkspaceCtx,
    _id: &str,
) -> Result<DispatchOutcome<Option<String>>, DispatchError> {
    DispatchWrapper::invoke(&ARTIFACT_STABILITY, "artifact-get", || {
        // WHERE clause shape: workspace_id = ctx.workspace_id() AND id = $2
        // ctx.workspace_id() is the WHERE-clause discriminator (R-0006-d).
        // Full sqlx execution wired in Task 5; shape is lint-compliant now.
        let _workspace_id = ctx.workspace_id();
        let _query = "SELECT id, type_name, frontmatter, body FROM artifacts \
                      WHERE workspace_id = $1 AND id = $2";
        todo!("artifact-get: storage wired in Task 5")
    })
}

/// `artifact-list` — lists artifacts matching the given type and filter criteria.
///
/// The WHERE clause includes `workspace_id = ctx.workspace_id()` to scope the
/// query to the caller's workspace (R-0006-d). Storage wiring lands in Task 5.
///
/// R-0012-a, R-0006-a, R-0006-d
pub fn artifact_list(
    ctx: WorkspaceCtx,
    _type_name: &str,
    _filters: Json,
) -> Result<DispatchOutcome<Vec<String>>, DispatchError> {
    DispatchWrapper::invoke(&ARTIFACT_STABILITY, "artifact-list", || {
        // WHERE clause shape: workspace_id = ctx.workspace_id() AND type_name = $2
        // ctx.workspace_id() is the WHERE-clause discriminator (R-0006-d).
        // Full sqlx execution wired in Task 5; shape is lint-compliant now.
        let _workspace_id = ctx.workspace_id();
        let _query = "SELECT id, type_name, frontmatter, body FROM artifacts \
                      WHERE workspace_id = $1 AND type_name = $2";
        todo!("artifact-list: storage wired in Task 5")
    })
}

/// `artifact-delete` — permanently deletes an artifact.
///
/// Opt-in: only available when `host_fns.required` declares this capability
/// (R-0003-g).
///
/// R-0012-a, R-0003-g, R-0006-a
pub fn artifact_delete(
    _ctx: WorkspaceCtx,
    _id: &str,
) -> Result<DispatchOutcome<()>, DispatchError> {
    DispatchWrapper::invoke(&ARTIFACT_STABILITY, "artifact-delete", || {
        todo!("artifact-delete: stub — storage wired in Task 5")
    })
}

// ---------------------------------------------------------------------------
// metrics interface
// ---------------------------------------------------------------------------

/// Stability constant for `metrics` functions.
const METRICS_STABILITY: Stability = Stability::Stable;

/// `metrics-record` — records a single metric observation.
///
/// R-0012-a, R-0006-a
pub fn metrics_record(
    _ctx: WorkspaceCtx,
    _verb: &str,
    _duration_ms: u64,
    _outcome: &str,
) -> Result<DispatchOutcome<()>, DispatchError> {
    DispatchWrapper::invoke(&METRICS_STABILITY, "metrics-record", || {
        todo!("metrics-record: stub — metrics sink wired in later task")
    })
}

// ---------------------------------------------------------------------------
// log interface
// ---------------------------------------------------------------------------

/// Stability constant for `log` functions.
const LOG_STABILITY: Stability = Stability::Stable;

/// `log-emit` — emits a structured log line.
///
/// R-0012-a, R-0006-a
pub fn log_emit(
    _ctx: WorkspaceCtx,
    _level: &str,
    _message: &str,
    _context: Option<Json>,
) -> Result<DispatchOutcome<()>, DispatchError> {
    DispatchWrapper::invoke(&LOG_STABILITY, "log-emit", || {
        todo!("log-emit: stub — log sink wired in later task")
    })
}

// ---------------------------------------------------------------------------
// event interface
// ---------------------------------------------------------------------------

/// Stability constant for `event` functions.
const EVENT_STABILITY: Stability = Stability::Stable;

/// `event-emit` — emits a versioned domain event.
///
/// R-0012-a, R-0006-a
pub fn event_emit(
    _ctx: WorkspaceCtx,
    _event_type: &str,
    _event_version: u16,
    _payload: Json,
) -> Result<DispatchOutcome<()>, DispatchError> {
    DispatchWrapper::invoke(&EVENT_STABILITY, "event-emit", || {
        todo!("event-emit: stub — event bus wired in later task")
    })
}

// ---------------------------------------------------------------------------
// projection interface
// ---------------------------------------------------------------------------

/// Stability constant for `projection` functions.
const PROJECTION_STABILITY: Stability = Stability::Stable;

/// `projection-emit` — emits a named projection update.
///
/// Workspace is derived from `ctx`; workspace-id is never an explicit param
/// (R-0003-d).
///
/// R-0012-a, R-0003-d, R-0006-a
pub fn projection_emit(
    _ctx: WorkspaceCtx,
    _projection_name: &str,
    _data: Json,
) -> Result<DispatchOutcome<()>, DispatchError> {
    DispatchWrapper::invoke(&PROJECTION_STABILITY, "projection-emit", || {
        todo!("projection-emit: stub — projection sink wired in later task")
    })
}

// ---------------------------------------------------------------------------
// sampling interface (@unstable)
// ---------------------------------------------------------------------------

/// Stability constant for `sampling` functions — @unstable(feature = sampling-v0).
const SAMPLING_STABILITY: Stability = Stability::Unstable {
    feature: "sampling-v0",
};

/// `sampling-request` — requests an LLM sampling inference.
///
/// `context_ids` carries opaque artifact ID references; the host does not
/// resolve them to bodies inside this call (R-0012-b).
///
/// R-0012-b, R-0006-a
pub fn sampling_request(
    _ctx: WorkspaceCtx,
    _context_ids: Vec<String>,
    _prompt: &str,
) -> Result<DispatchOutcome<Option<String>>, DispatchError> {
    DispatchWrapper::invoke(&SAMPLING_STABILITY, "sampling-request", || {
        todo!("sampling-request: stub — LLM integration wired in later task")
    })
}

// ---------------------------------------------------------------------------
// secrets interface (read-only)
// ---------------------------------------------------------------------------

/// Stability constant for `secrets` functions.
const SECRETS_STABILITY: Stability = Stability::Stable;

/// `secrets-get` — retrieves a secret value by name.
///
/// Read-only; no write path to the secrets store at V0 (R-0012-c).
///
/// R-0012-c, R-0006-a
pub fn secrets_get(
    _ctx: WorkspaceCtx,
    _name: &str,
) -> Result<DispatchOutcome<Option<String>>, DispatchError> {
    DispatchWrapper::invoke(&SECRETS_STABILITY, "secrets-get", || {
        todo!("secrets-get: stub — secrets store wired in later task")
    })
}
