//! Admin-token generation, storage, and rotation (R-0008, R-0009).
//!
//! # Cryptographic choices
//!
//! - **Generation (R-0008-a):** 32 bytes from `rand::rngs::OsRng` (CSPRNG),
//!   base64url-encoded without padding via `base64::engine::general_purpose::URL_SAFE_NO_PAD`.
//!   The result is always exactly 43 characters.
//!
//! - **Hashing (R-0008-b):** BLAKE3(decoded_token_bytes) → 32-byte hash stored
//!   as BYTEA. The raw token bytes are never stored.
//!
//! - **Authentication (R-0008-b):** a presented token is authenticated by hashing
//!   it (`hash_presented` → BLAKE3) and looking the row up by that hash against the
//!   unique `admin_tokens.token_hash` column (`lookup_by_hash`). No constant-time
//!   byte comparison is performed or needed on this path: the admin token is a
//!   256-bit CSPRNG value (R-0008-a) and the match is a unique-index lookup on its
//!   BLAKE3 hash, so comparison-timing attacks do not apply. Constant-time
//!   comparison is still required where it does apply — the signing-chain
//!   verification path per P-0005 (see `signing/verify.rs`), not here.
//!
//! - **No logging of token material:** `AdminToken` has a hand-written `Debug`
//!   that emits only `AdminToken(<redacted>)`. No `Display` impl exists.
//!
//! # Rotation ordering guarantee (R-0008-g, R-0009-i)
//!
//! `rotate()` constructs `TokenRotatedEvent` from the old row's data BEFORE
//! issuing the DELETE. Transaction ordering: new token INSERT first, then old
//! token DELETE. The event value is returned BEFORE the caller can observe any
//! change in the DB — the return of `(AdminToken, TokenRotatedEvent)` is the
//! observable ordering seam. After `rotate()` returns, a `lookup_by_hash` on
//! the old hash returns `Ok(None)` — no grace period (R-0009-i).
//!
//! # DELETE grant note
//!
//! `rotate()` accepts a `&PgPool` supplied by the caller. In tests this is
//! `engine.pool` (the mnemra_app role, which owns the tables). The `mnemra_host_fns`
//! role has no DELETE grant at V0 (per cross-dispatch note 4). No DELETE grant
//! is widened here. A caller providing a pool without DELETE will receive a
//! sqlx error — that is correct behavior and must be handled by the caller.
//!
//! # File-mode mechanics (R-0008-e)
//!
//! `write_token_file(token, path)` creates/truncates the file at `path` with
//! mode 0600 before writing content (create → chmod → write sequence on Unix).
//! `check_token_file_mode(path)` returns a structured error if the file is
//! world-readable (mode & 0o177 != 0) or the UID does not match.
//!
//! Path resolution for the default path lives in `default_token_file_path()`:
//! reads `MNEMRA_TOKEN_FILE` env var, falls back to `~/.config/mnemra/token`.

use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use blake3::Hasher as Blake3Hasher;
use chrono::{DateTime, Utc};
use rand::TryRng;
use sqlx::PgPool;
use uuid::Uuid;

use std::fmt;
use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// A generated admin token: 32 raw bytes, base64url-encoded (no padding).
///
/// # Invariant (R-0008-a)
///
/// The inner string is ALWAYS 43 characters, URL_SAFE_NO_PAD alphabet.
/// Raw token bytes are accessible via `as_bytes()` (decoded) for hashing;
/// the encoded string is accessible via `as_str()` for file writes.
///
/// # Debug redaction
///
/// `Debug` is hand-written to emit `AdminToken(<redacted>)`. No `Display`
/// implementation exists — accidental format-string use will not compile.
pub struct AdminToken(String);

impl fmt::Debug for AdminToken {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "AdminToken(<redacted>)")
    }
}

impl AdminToken {
    /// The base64url-encoded token string (43 chars, no padding).
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Decode the base64url token to its 32 raw bytes.
    ///
    /// Panics only if the token was constructed outside this module with an
    /// invalid base64url string — impossible via `generate()`.
    pub(crate) fn decoded_bytes(&self) -> [u8; 32] {
        let decoded = URL_SAFE_NO_PAD
            .decode(&self.0)
            .expect("AdminToken always contains valid base64url (generated by generate())");
        let mut buf = [0u8; 32];
        buf.copy_from_slice(&decoded);
        buf
    }
}

/// The BLAKE3 hash of an `AdminToken`'s raw bytes, for DB storage (R-0008-b).
///
/// The inner `[u8; 32]` is the 32-byte BLAKE3 hash output. Raw token bytes
/// are never exposed through this type.
#[derive(Debug, Clone)]
pub struct TokenHash(pub [u8; 32]);

impl TokenHash {
    /// The raw hash bytes for DB storage (BYTEA).
    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}

/// A row fetched from `admin_tokens` (mirrors the schema's six columns).
///
/// `token_hash` is a `Vec<u8>` to match BYTEA return from sqlx.
#[derive(Debug)]
pub struct TokenRow {
    pub id: Uuid,
    pub token_hash: Vec<u8>,
    pub workspace_id: Uuid,
    pub scopes: Vec<String>,
    pub created_at: DateTime<Utc>,
    pub rotated_at: Option<DateTime<Utc>>,
}

/// A rotation event emitted (as a return value) BEFORE the old row is deleted.
///
/// # Ordering contract (R-0008-g)
///
/// `rotate()` constructs this event from the old row's data before issuing
/// the DELETE. The event is returned to the caller; the caller observes it
/// before any DB state change is visible (both happen within one transaction,
/// but the return value logically "precedes" the committed deletion).
#[derive(Debug)]
pub struct TokenRotatedEvent {
    /// The rotated (old) token's `id`.
    pub token_id: Uuid,
    /// The workspace this token belongs to.
    pub workspace_id: Uuid,
}

/// Error type for rotation failures.
#[derive(Debug)]
pub enum RotateError {
    /// The old token row was not found by the given `old_token_id`.
    TokenNotFound(Uuid),
    /// A database error occurred during rotation.
    Db(sqlx::Error),
}

impl fmt::Display for RotateError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            RotateError::TokenNotFound(id) => {
                write!(f, "admin token not found: {id}")
            }
            RotateError::Db(e) => write!(f, "rotation db error: {e}"),
        }
    }
}

impl std::error::Error for RotateError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            RotateError::Db(e) => Some(e),
            RotateError::TokenNotFound(_) => None,
        }
    }
}

impl From<sqlx::Error> for RotateError {
    fn from(e: sqlx::Error) -> Self {
        RotateError::Db(e)
    }
}

// ---------------------------------------------------------------------------
// Token file errors
// ---------------------------------------------------------------------------

/// Error returned by `check_token_file_mode`.
#[derive(Debug)]
pub enum TokenFileModeError {
    /// The file is not mode 0600 (world-readable or group-readable).
    WrongMode { actual: u32 },
    /// The file UID does not match the current process UID.
    WrongOwner { file_uid: u32, current_uid: u32 },
    /// An IO error occurred reading the file metadata.
    Io(std::io::Error),
}

impl fmt::Display for TokenFileModeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenFileModeError::WrongMode { actual } => {
                write!(
                    f,
                    "token file has wrong mode {actual:#o}, expected 0600 (R-0008-e)"
                )
            }
            TokenFileModeError::WrongOwner {
                file_uid,
                current_uid,
            } => {
                write!(
                    f,
                    "token file owner uid {file_uid} != current uid {current_uid} (R-0008-e)"
                )
            }
            TokenFileModeError::Io(e) => write!(f, "token file io error: {e}"),
        }
    }
}

impl std::error::Error for TokenFileModeError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            TokenFileModeError::Io(e) => Some(e),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Generate a fresh admin token: 32 bytes from OsRng → base64url-encode (no padding).
///
/// The returned token's string representation is exactly 43 characters,
/// URL_SAFE_NO_PAD alphabet (R-0008-a). The raw bytes are never stored;
/// callers use `hash()` for DB storage.
pub fn generate() -> AdminToken {
    let mut raw = [0u8; 32];
    // rand 0.10: OsRng is now SysRng (re-exported from getrandom).
    rand::rngs::SysRng
        .try_fill_bytes(&mut raw)
        .expect("SysRng (OS CSPRNG) must not fail");
    let encoded = URL_SAFE_NO_PAD.encode(raw);
    debug_assert_eq!(encoded.len(), 43, "base64url of 32 bytes must be 43 chars");
    AdminToken(encoded)
}

/// Hash token bytes for DB storage: BLAKE3(decoded_token_bytes) → 32-byte hash.
///
/// Accepts `&AdminToken` (not raw bytes) to prevent accidental hashing of the
/// base64-encoded string instead of the decoded bytes (R-0008-b).
pub fn hash(token: &AdminToken) -> TokenHash {
    let decoded = token.decoded_bytes();
    let hash_output = Blake3Hasher::new().update(&decoded).finalize();
    TokenHash(*hash_output.as_bytes())
}

/// Rotate a token: construct the rotation event from the old row, then execute
/// INSERT new + DELETE old in one transaction. Returns the new token and the
/// rotation event.
///
/// # Ordering (R-0008-g, R-0009-i)
///
/// The `TokenRotatedEvent` is constructed from the old row's data BEFORE the
/// DELETE is issued. Transaction ordering: INSERT new row first, then DELETE
/// old row, then commit. The event is returned; after return, `lookup_by_hash`
/// on the old hash returns `Ok(None)` with no grace period (R-0009-i).
///
/// # Pool note
///
/// The caller must supply a pool whose role has DELETE on `admin_tokens`.
/// In production that is the `mnemra_app` owner role. The `mnemra_host_fns`
/// role does NOT have DELETE — this is not widened here (see module doc).
pub async fn rotate(
    pool: &PgPool,
    old_token_id: Uuid,
) -> Result<(AdminToken, TokenRotatedEvent), RotateError> {
    // Fetch the old row to confirm it exists and to derive workspace_id + scopes.
    // This SELECT is intentionally outside the transaction: admin_tokens.workspace_id
    // and scopes are immutable after row creation (only rotated_at is ever UPDATEd),
    // so there is no TOCTOU risk from reading them before the transaction opens.
    let old_row: Option<(Uuid, Vec<String>)> =
        sqlx::query_as("SELECT workspace_id, scopes FROM admin_tokens WHERE id = $1")
            .bind(old_token_id)
            .fetch_optional(pool)
            .await?;

    let (workspace_id, scopes) = old_row.ok_or(RotateError::TokenNotFound(old_token_id))?;

    // Construct the rotation event BEFORE the DELETE (R-0008-g ordering).
    // The event carries the old token's id and workspace_id as its payload,
    // both sourced from the old row (strengthens R-0008-g: event genuinely
    // reflects the rotated token's identity, not any caller-supplied value).
    let event = TokenRotatedEvent {
        token_id: old_token_id,
        workspace_id,
    };

    // Generate the new token and its hash.
    let new_token = generate();
    let new_hash = hash(&new_token);
    let new_id = Uuid::new_v4();

    // Execute: INSERT new, DELETE old — both in one transaction.
    let mut tx = pool.begin().await?;

    sqlx::query(
        "INSERT INTO admin_tokens (id, token_hash, workspace_id, scopes)
         VALUES ($1, $2, $3, $4)",
    )
    .bind(new_id)
    .bind(new_hash.as_bytes())
    .bind(workspace_id)
    .bind(&scopes)
    .execute(&mut *tx)
    .await?;

    // UPDATE rotated_at on old row before deleting — records rotation timestamp
    // for audit purposes (rotated_at is otherwise NULL for never-rotated tokens).
    sqlx::query("UPDATE admin_tokens SET rotated_at = now() WHERE id = $1")
        .bind(old_token_id)
        .execute(&mut *tx)
        .await?;

    sqlx::query("DELETE FROM admin_tokens WHERE id = $1")
        .bind(old_token_id)
        .execute(&mut *tx)
        .await?;

    tx.commit().await?;

    // Return event + new token. After this return, lookup_by_hash(old_hash) → Ok(None).
    Ok((new_token, event))
}

/// Hash a presented raw token string to a `TokenHash` without constructing an `AdminToken`.
///
/// # Auth-wiring gap (Task 23)
///
/// `AdminToken`'s inner field is private; there is no public path to construct
/// one from a caller-supplied string. The MCP DF-auth-check receives a raw
/// token string from `_meta.token` and needs to hash it for a DB lookup without
/// an `AdminToken` in hand.
///
/// This function decodes the base64url string and hashes the raw bytes exactly
/// as `hash(&AdminToken)` would. Returns `None` if the string is not valid
/// base64url or does not decode to exactly 32 bytes — the caller MUST treat
/// `None` as an auth failure.
///
/// # Security note (R-0004-h)
///
/// The token string MUST NOT appear in any log, metric, event, or error
/// message. Pass `token_str` into this function; do not format it elsewhere.
pub fn hash_presented(token_str: &str) -> Option<TokenHash> {
    let decoded = URL_SAFE_NO_PAD.decode(token_str).ok()?;
    if decoded.len() != 32 {
        return None;
    }
    let mut buf = [0u8; 32];
    buf.copy_from_slice(&decoded);
    let hash_output = Blake3Hasher::new().update(&buf).finalize();
    Some(TokenHash(*hash_output.as_bytes()))
}

/// Look up a token row by its BLAKE3 hash.
///
/// Returns `Ok(None)` if not found. After rotation, a lookup by the old token's
/// hash returns `Ok(None)` immediately — no grace period (R-0009-i).
pub async fn lookup_by_hash(
    hash: &TokenHash,
    pool: &PgPool,
) -> Result<Option<TokenRow>, sqlx::Error> {
    let row = sqlx::query_as::<
        _,
        (
            Uuid,
            Vec<u8>,
            Uuid,
            Vec<String>,
            DateTime<Utc>,
            Option<DateTime<Utc>>,
        ),
    >(
        "SELECT id, token_hash, workspace_id, scopes, created_at, rotated_at
         FROM admin_tokens
         WHERE token_hash = $1",
    )
    .bind(hash.as_bytes())
    .fetch_optional(pool)
    .await?;

    Ok(row.map(
        |(id, token_hash, workspace_id, scopes, created_at, rotated_at)| TokenRow {
            id,
            token_hash,
            workspace_id,
            scopes,
            created_at,
            rotated_at,
        },
    ))
}

// ---------------------------------------------------------------------------
// Token file API (R-0008-e)
// ---------------------------------------------------------------------------

/// Write the admin token to a file at `path` with mode 0600 (R-0008-e).
///
/// The file is created (or truncated) with mode 0600 before content is written.
/// The create → chmod → write sequence ensures no window where the file is
/// readable at a wider mode.
///
/// # Test usage
///
/// Pass a path inside a `tempdir()` in tests. The `MNEMRA_TOKEN_FILE` env-var
/// resolution lives in `default_token_file_path()`.
pub fn write_token_file(token: &AdminToken, path: &Path) -> Result<(), std::io::Error> {
    use std::fs::OpenOptions;
    use std::io::Write;
    use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};

    // Create parent directory if it does not exist.
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    // Open with mode 0600 at creation time — no wider window.
    let mut file = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .mode(0o600)
        .open(path)?;

    file.write_all(token.as_str().as_bytes())?;
    file.flush()?;

    // Explicit chmod ensures mode on an existing file being truncated is 0600.
    let permissions = std::fs::Permissions::from_mode(0o600);
    std::fs::set_permissions(path, permissions)?;

    Ok(())
}

/// Check that the token file at `path` has mode 0600 and is owned by the
/// current process UID (R-0008-e).
///
/// Returns `Err(TokenFileModeError::WrongMode)` if the file is world-readable
/// or group-readable (any bit beyond user read+write is set). Returns
/// `Err(TokenFileModeError::WrongOwner)` if the owner UID differs.
pub fn check_token_file_mode(path: &Path) -> Result<(), TokenFileModeError> {
    use std::os::unix::fs::MetadataExt;
    use std::os::unix::fs::PermissionsExt;

    let metadata = std::fs::metadata(path).map_err(TokenFileModeError::Io)?;

    let mode = metadata.permissions().mode() & 0o777;
    if mode != 0o600 {
        return Err(TokenFileModeError::WrongMode { actual: mode });
    }

    let file_uid = metadata.uid();
    let current_uid = libc_getuid();
    if file_uid != current_uid {
        return Err(TokenFileModeError::WrongOwner {
            file_uid,
            current_uid,
        });
    }

    Ok(())
}

/// Resolve the default token file path.
///
/// Path resolution order (R-0008-e):
/// 1. `MNEMRA_TOKEN_FILE` env var, if set and non-empty.
/// 2. `~/.config/mnemra/token` via HOME expansion.
///
/// Returns `None` if HOME is not set and `MNEMRA_TOKEN_FILE` is not set.
pub fn default_token_file_path() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("MNEMRA_TOKEN_FILE")
        && !p.is_empty()
    {
        return Some(PathBuf::from(p));
    }
    let home = std::env::var("HOME").ok()?;
    Some(PathBuf::from(home).join(".config/mnemra/token"))
}

/// Thin wrapper around `libc::getuid()` to get the current process UID.
/// Isolated here to keep `unsafe` contained.
#[allow(unsafe_code)]
fn libc_getuid() -> u32 {
    // SAFETY: getuid() is always safe to call.
    unsafe { libc::getuid() }
}

// ---------------------------------------------------------------------------
// Unit tests (internal)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{LazyLock, Mutex};
    use tempfile::tempdir;

    /// Serializes any test that mutates process environment variables
    /// (`MNEMRA_TOKEN_FILE`, `HOME`) within this binary.
    ///
    /// `std::env::set_var`/`remove_var` mutate process-global state; under
    /// `cargo test` (multiple threads in one binary) two tests racing on the
    /// same vars produce nondeterministic results. Holding this lock for the
    /// duration of any env-mutating test serializes them (workspace
    /// `set_var_test_flake` rule — lock-serialize rather than ban env tests).
    /// Independent of any other test binary's locks; the binary is the race
    /// boundary because env is per-process.
    static ENV_LOCK: LazyLock<Mutex<()>> = LazyLock::new(|| Mutex::new(()));

    /// RAII guard: snapshot one env var on construction, restore it on drop.
    ///
    /// `None` snapshot means "was unset" → restored by `remove_var`. Restoring
    /// on drop keeps env mutations from leaking into sibling tests even if an
    /// assertion panics mid-test.
    struct EnvVarGuard {
        key: &'static str,
        prev: Option<String>,
    }

    impl EnvVarGuard {
        /// Snapshot `key`'s current value (so it can be restored on drop).
        fn capture(key: &'static str) -> Self {
            let prev = std::env::var(key).ok();
            Self { key, prev }
        }

        /// Set `key` to `value` for the lifetime of the guard.
        fn set(&self, value: &str) {
            // SAFETY: env mutation is serialized by `ENV_LOCK` (held by the
            // caller for the whole test); no other thread reads/writes env
            // concurrently. `#[allow(unsafe_code)]` matches the `libc_getuid`
            // convention in this file (env::set_var is `unsafe fn` in edition 2024).
            #[allow(unsafe_code)]
            unsafe {
                std::env::set_var(self.key, value);
            }
        }

        /// Remove `key` from the environment for the lifetime of the guard.
        fn unset(&self) {
            // SAFETY: see `set` — env mutation is serialized by `ENV_LOCK`.
            #[allow(unsafe_code)]
            unsafe {
                std::env::remove_var(self.key);
            }
        }
    }

    impl Drop for EnvVarGuard {
        fn drop(&mut self) {
            // SAFETY: see `set` — restoration runs under the same serialization
            // (the lock outlives the guards within each test).
            #[allow(unsafe_code)]
            unsafe {
                match &self.prev {
                    Some(v) => std::env::set_var(self.key, v),
                    None => std::env::remove_var(self.key),
                }
            }
        }
    }

    // -----------------------------------------------------------------------
    // generate / hash
    // -----------------------------------------------------------------------

    #[test]
    fn generate_produces_43_char_base64url() {
        let token = generate();
        assert_eq!(
            token.as_str().len(),
            43,
            "generated token must be 43 chars (base64url of 32 bytes, no padding)"
        );
        // All chars must be base64url alphabet (A-Z, a-z, 0-9, -, _)
        for ch in token.as_str().chars() {
            assert!(
                ch.is_ascii_alphanumeric() || ch == '-' || ch == '_',
                "non-base64url char '{ch}' in generated token"
            );
        }
    }

    #[test]
    fn generate_produces_distinct_tokens() {
        let t1 = generate();
        let t2 = generate();
        assert_ne!(
            t1.as_str(),
            t2.as_str(),
            "two consecutive generate() calls must produce distinct tokens"
        );
    }

    #[test]
    fn hash_produces_32_bytes() {
        let token = generate();
        let h = hash(&token);
        assert_eq!(h.0.len(), 32, "BLAKE3 hash must be 32 bytes");
    }

    #[test]
    fn hash_is_deterministic() {
        let token = generate();
        let h = hash(&token);
        let h2 = hash(&token);
        // Two hashes of the same token bytes must be identical.
        assert_eq!(h.0, h2.0, "hash must be deterministic");
    }

    #[test]
    fn debug_does_not_leak_token_material() {
        let token = generate();
        let debug_str = format!("{:?}", token);
        assert!(
            debug_str.contains("<redacted>"),
            "AdminToken Debug must contain '<redacted>', got: {debug_str}"
        );
        assert!(
            !debug_str.contains(token.as_str()),
            "AdminToken Debug must NOT contain the token string"
        );
    }

    // -----------------------------------------------------------------------
    // write_token_file / check_token_file_mode
    // -----------------------------------------------------------------------

    #[test]
    fn write_token_file_creates_mode_600() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempdir().expect("tempdir");
        let path = dir.path().join("token");
        let token = generate();

        write_token_file(&token, &path).expect("write_token_file failed");

        let metadata = std::fs::metadata(&path).expect("metadata");
        let mode = metadata.permissions().mode() & 0o777;
        assert_eq!(
            mode, 0o600,
            "token file must be mode 0600 after write_token_file"
        );
    }

    #[test]
    fn write_token_file_content_is_token_string() {
        let dir = tempdir().expect("tempdir");
        let path = dir.path().join("token");
        let token = generate();

        write_token_file(&token, &path).expect("write_token_file failed");

        let content = std::fs::read_to_string(&path).expect("read back");
        assert_eq!(
            content,
            token.as_str(),
            "token file content must be the base64url token string"
        );
    }

    #[test]
    fn check_token_file_mode_accepts_600() {
        let dir = tempdir().expect("tempdir");
        let path = dir.path().join("token");
        let token = generate();

        write_token_file(&token, &path).expect("write_token_file failed");

        check_token_file_mode(&path)
            .expect("check_token_file_mode should accept a 0600 file written by write_token_file");
    }

    #[test]
    fn check_token_file_mode_rejects_world_readable() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempdir().expect("tempdir");
        let path = dir.path().join("token");
        let token = generate();

        write_token_file(&token, &path).expect("write_token_file failed");

        // Widen to 0644 to simulate a misconfigured file.
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o644))
            .expect("set_permissions");

        let err = check_token_file_mode(&path)
            .expect_err("check_token_file_mode must reject a 0644 file");

        match err {
            TokenFileModeError::WrongMode { actual } => {
                assert_eq!(actual, 0o644, "wrong mode value in error")
            }
            other => panic!("expected WrongMode, got {:?}", other),
        }
    }

    // -----------------------------------------------------------------------
    // default_token_file_path
    // -----------------------------------------------------------------------

    /// `default_token_file_path()` honours the `MNEMRA_TOKEN_FILE` override when
    /// set+non-empty, and otherwise falls back to `$HOME/.config/mnemra/token`
    /// (R-0008-e, T10.5).
    ///
    /// Both branches are asserted with exact equality (not `.ends_with`) against
    /// a known tempdir HOME, so a regression in either clause fails this test:
    /// dropping the override would make the override case return the HOME path;
    /// changing the fallback suffix would break the fallback case.
    ///
    /// Env mutation is serialized via `ENV_LOCK` and every mutated var is
    /// restored on drop (`set_var_test_flake` workspace rule — env vars are
    /// process-global, so the lock and the file-local punt-replaced test share
    /// one serialization point). The parked clauses (owner-UID negative;
    /// startup-mode-resolves-same-override) have no clean assertion surface and
    /// stay out of scope.
    #[test]
    fn default_token_file_path_uses_mnemra_token_file_env() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|p| p.into_inner());

        // Snapshot + auto-restore both vars this test mutates.
        let token_file = EnvVarGuard::capture("MNEMRA_TOKEN_FILE");
        let home = EnvVarGuard::capture("HOME");

        // --- Branch 1: MNEMRA_TOKEN_FILE override (set + non-empty) wins. ---
        let override_dir = tempdir().expect("tempdir for override path");
        let override_path = override_dir.path().join("custom-token");
        let override_str = override_path.to_string_lossy().into_owned();
        token_file.set(&override_str);
        // HOME also set, to prove the override takes precedence over the fallback.
        let home_dir = tempdir().expect("tempdir for HOME");
        home.set(&home_dir.path().to_string_lossy());

        let resolved = default_token_file_path()
            .expect("override branch: MNEMRA_TOKEN_FILE set → must return Some");
        assert_eq!(
            resolved, override_path,
            "R-0008-e: when MNEMRA_TOKEN_FILE is set+non-empty, \
             default_token_file_path() must return exactly that path (override wins over HOME)"
        );

        // --- Branch 2: empty MNEMRA_TOKEN_FILE is ignored → HOME fallback. ---
        // An empty value must NOT be treated as an override (the `!p.is_empty()`
        // guard); resolution falls through to $HOME/.config/mnemra/token.
        token_file.set("");
        let expected_fallback = home_dir.path().join(".config/mnemra/token");

        let resolved_fallback =
            default_token_file_path().expect("fallback branch: HOME set → must return Some");
        assert_eq!(
            resolved_fallback, expected_fallback,
            "R-0008-e: when MNEMRA_TOKEN_FILE is empty, \
             default_token_file_path() must fall back to exactly $HOME/.config/mnemra/token"
        );

        // --- Branch 2b: MNEMRA_TOKEN_FILE fully unset → same HOME fallback. ---
        token_file.unset();
        let resolved_unset =
            default_token_file_path().expect("unset branch: HOME set → must return Some");
        assert_eq!(
            resolved_unset, expected_fallback,
            "R-0008-e: when MNEMRA_TOKEN_FILE is unset, \
             default_token_file_path() must fall back to $HOME/.config/mnemra/token"
        );

        // Guards drop here → MNEMRA_TOKEN_FILE and HOME restored to prior values.
    }
}
